In [2]:
import pandas as pd

# 1. Carichiamo i tre file (saltando le prime due righe di commento con skiprows=2)
# Assicurati che i nomi dei file corrispondano a quelli nella tua cartella

# Carica Nd-LSCO (Temperature 4K, 40K, 80K)
moesm2 = pd.read_csv('41567_2022_1763_MOESM2_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_4K', 'rho_4K', 'B_40K', 'rho_40K', 'B_80K', 'rho_80K'])

# Carica LSCO S1 (Temperature 4K, 40K, 80K)
moesm4 = pd.read_csv('41567_2022_1763_MOESM4_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_4K', 'rho_4K', 'B_40K', 'rho_40K', 'B_80K', 'rho_80K'])

# Carica il file a 30K per entrambi
moesm6 = pd.read_csv('41567_2022_1763_MOESM6_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_S1_30K', 'rho_S1_30K', 'B_S2_30K', 'rho_S2_30K', 'B_Nd_30K', 'rho_Nd_30K'])

# 2. Creiamo i dataset finali unendo le colonne di MOESM6 ai rispettivi file
# Uniamo Nd-LSCO (MOESM2 + le ultime due colonne di MOESM6)
nd_lsco_completo = pd.concat([moesm2, moesm6[['B_Nd_30K', 'rho_Nd_30K']]], axis=1)

# Uniamo LSCO S1 (MOESM4 + le prime due colonne di MOESM6)
lsco_s1_completo = pd.concat([moesm4, moesm6[['B_S1_30K', 'rho_S1_30K']]], axis=1)

# 3. Mostriamo l'anteprima delle tabelle unite
print("=== Anteprima Nd-LSCO Completo ===")
display(nd_lsco_completo.head())

print("\n=== Anteprima LSCO S1 Completo ===")
display(lsco_s1_completo.head())

# (Opzionale) De-commenta queste righe per salvare i nuovi file sul tuo computer
# nd_lsco_completo.to_csv('Nd_LSCO_Tutte_Temperature.csv', index=False)
# lsco_s1_completo.to_csv('LSCO_S1_Tutte_Temperature.csv', index=False)

=== Anteprima Nd-LSCO Completo ===

,B_4K,rho_4K,B_40K,rho_40K,B_80K,rho_80K,B_Nd_30K,rho_Nd_30K
0,13.406,9.0745e-01,0.10260,1.0009,1.0006e-01,9.9997e-01,8.4879e+01,1.1598e+00
1,13.415,9.0960e-01,0.10271,1.0003,1.0019e-01,9.9997e-01,8.4878e+01,1.1600e+00
2,13.425,9.1018e-01,0.10282,1.0010,1.0033e-01,9.9991e-01,8.4877e+01,1.1601e+00
3,13.435,9.1152e-01,0.10293,1.0006,1.0047e-01,9.9991e-01,8.4876e+01,1.1601e+00
4,13.445,9.1274e-01,0.10304,1.0007,1.0061e-01,9.9991e-01,8.4876e+01,1.1599e+00

=== Anteprima LSCO S1 Completo ===

,B_4K,rho_4K,B_40K,rho_40K,B_80K,rho_80K,B_S1_30K,rho_S1_30K
0,23.051,9.1183e-01,0.020020,1.0005,2.0047e-02,1.0002e+00,0.20022,9.9503e-01
1,23.069,9.1443e-01,0.020098,1.0005,2.0126e-02,1.0002e+00,0.20048,9.9501e-01
2,23.088,9.1684e-01,0.020178,1.0005,2.0206e-02,1.0002e+00,0.20074,9.9502e-01
3,23.106,9.1926e-01,0.020256,1.0005,2.0287e-02,1.0002e+00,0.20100,9.9501e-01
4,23.125,9.2183e-01,0.020335,1.0005,2.0367e-02,1.0002e+00,0.20125,9.9502e-01

In [3]:
import pandas as pd

# 1. Carichiamo i tre file
moesm2 = pd.read_csv('41567_2022_1763_MOESM2_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_4K', 'rho_4K', 'B_40K', 'rho_40K', 'B_80K', 'rho_80K'])

moesm4 = pd.read_csv('41567_2022_1763_MOESM4_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_4K', 'rho_4K', 'B_40K', 'rho_40K', 'B_80K', 'rho_80K'])

moesm6 = pd.read_csv('41567_2022_1763_MOESM6_ESM.txt', sep='\t', header=None, skiprows=2, 
                     names=['B_S1_30K', 'rho_S1_30K', 'B_S2_30K', 'rho_S2_30K', 'B_Nd_30K', 'rho_Nd_30K'])

# 2. Uniamo le colonne
nd_lsco_completo = pd.concat([moesm2, moesm6[['B_Nd_30K', 'rho_Nd_30K']]], axis=1)
lsco_s1_completo = pd.concat([moesm4, moesm6[['B_S1_30K', 'rho_S1_30K']]], axis=1)

# 3. Salviamo in formato .txt (usando la tabulazione come separatore)
nd_lsco_completo.to_csv('Nd_LSCO_Completo.txt', sep='\t', index=False)
lsco_s1_completo.to_csv('LSCO_S1_Completo.txt', sep='\t', index=False)

print("File .txt salvati con successo nella cartella di Jupyter!")

File .txt salvati con successo nella cartella di Jupyter!